### ISSUE TITLE
Feature: good for newcomers issues

### ISSUE THREAD

**Issue by shawnharmsen** [indexsupply/code#189]
do you have some low lying fruit for newcomers to help out with ser?
looking at this and trueblocks to solve some self hosted indexing urges I have
will be utilizing codebooga and gpt4 heavily

**Comment by ryandotsmith** [comment]
@shawnharmsen Hi. Great question. I am currently working off a text file on my computer. One day soon I will start adding more public issues so that people can get a sense of what is coming and where areas of collaboration might exist.

In the meantime, is there something in particular that is missing from e2pg that you will need? Happy to work on your requirements. If we need to add something, I can even work with you on how best to approach the change.

**Comment by shawnharmsen** [comment]
sounds good! will go through and see if there is something I can grok and hopefully contribute

**Comment by ryandotsmith** [comment]
> sounds good! will go through and see if there is something I can grok and hopefully contribute

are you using e2pg? what's your experience been like so far?

**Comment by shawnharmsen** [comment]
no ser not yet have been satisfied with cryo but looking to expand and following up on spamming you continuously a few months prior. Will dig in and grok the shit out of things this week ( translation: use bloop to understand and gpt4 and oobaboobababboobabo coder

**Comment by ryandotsmith** [comment]
Ya know... One of the most valuable ways to contribute right now is to use the software to index events and report bugs. The primary code paths are starting to stabilize and so now I'm stress testing and hunting down bugs.

You could start by following the steps in the README and verify that it works. https://github.com/indexsupply/x/blob/main/docs/e2pg/readme.md

**Comment by shawnharmsen** [comment]
aaaaahhhh exactly wat I needed ty ser will run on my reth box soon and report back

**Comment by shawnharmsen** [comment]
do you have some estimates of how much storage required for mainnet?

assuming most have 4tb of which 3.4 to 3.6 available and reth taking up 2.1 to 2.2

need to figure out if need to move to another drive I think

**Comment by shawnharmsen** [comment]
quick comment as I try to grok this please

please include download link for linux
```bash
curl -LO https://indexsupply.net/bin/main/linux/amd64/e2pg
```
assuming I'm downloading it correctly

**Comment by ryandotsmith** [comment]
OK. So you are no longer hitting issues?

FWIW I just landed a diagnostics endpoint in #205. If you are having issues, you can open the dashboard and visit /diag.

Going to close this for now. Feel free to open if you hit new issues.
