### ISSUE TITLE
combined filters logic

### ISSUE THREAD

**Issue by 0xBigBoss** [indexsupply/code#239]
I couldn't find this in the docs, but am wondering how multiple filters on the same object work. e.g. here's a peek at my integration and it's event field.

```json
{
  "event": {
    "type": "event",
    "name": "Transfer",
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "from",
        "type": "address",
        "column": "f",
        "filter_op": "contains",
        "filter_ref": {
          "integration": "account_deployed",
          "column": "sender"
        }
      },
      {
        "indexed": true,
        "name": "to",
        "type": "address",
        "column": "t",
        "filter_op": "contains",
        "filter_ref": {
          "integration": "account_deployed",
          "column": "sender"
        }
      },
      {
        "indexed": false,
        "name": "value",
        "type": "uint256",
        "column": "v"
      }
    ]
  }
}
```

will it filter to only events that are `from` or `to` one of the `sender` in the `account_deployed` integratoin? or will it filter only where the `from` and `to` are the same `sender`?

**Comment by ryandotsmith** [comment]
Hello @0xBigBoss. Thank you for reporting this issue. You are correct. This behaviour was not defined.

In your example, the event will be saved if either the `from` or the `to` are equal to any `sender` in the `account_deployed` integration table. So they are combined using an `OR` operation. Is this acceptable for your use case?

I have also fixed the docs to describe the current behaviour.

**Comment by 0xBigBoss** [comment]
> Hello @0xBigBoss. Thank you for reporting this issue. You are correct. This behaviour was not defined.
> 
> In your example, the event will be saved if either the `from` or the `to` are equal to any `sender` in the `account_deployed` integration table. So they are combined using an `OR` operation. Is this acceptable for your use case?
> 
> I have also fixed the docs to describe the current behaviour.

I was going to try and finish my integrations today to see the real deal. You're description is exactly what we needed. Thanks for the prompt response.

**Comment by ryandotsmith** [comment]
Sounds good. Ping me if you run into any snags.
