### ISSUE TITLE
Indexing transaction nonces?

### ISSUE THREAD

**Issue by raster21** [indexsupply/code#264]
I couldn't find `tx_nonce` in the docs but did find a reference to it in the code: https://github.com/indexsupply/code/blob/3410a68dabb23215060910315fd6277f6df8db96/shovel/glf/filter.go#L110

I assume it's possible given that the response of `eth_getBlockByNumber` with Full Transaction Objects set to `true` returns the nonce information, but I could not find any documentation around this. Same for `maxPriorityFeePerGas`,, `maxFeePerGas` and `gasPrice`.

Thank you!

**Comment by ryandotsmith** [comment]
Thank you. Added `tx_nonce` and `tx_gas_price` and landed on main.

**Comment by raster21** [comment]
Amazing! I will give it a try. Thank you.
Any chance you could also add `MaxPriorityFeePerGas` and `MaxFeePerGas` for type 2 transactions?

**Comment by raster21** [comment]
@ryandotsmith I did a quick test and `tx_nonce` now appears in the db. However, filtering (using `eq`, `lt`, etc) is not working, all values always appear regardless of any filter operations.

**Comment by ryandotsmith** [comment]
> @ryandotsmith I did a quick test and `tx_nonce` now appears in the db. However, filtering (using `eq`, `lt`, etc) is not working, all values always appear regardless of any filter operations.

should be addressed in: 0686d65

**Comment by ryandotsmith** [comment]
> Amazing! I will give it a try. Thank you. Any chance you could also add `MaxPriorityFeePerGas` and `MaxFeePerGas` for type 2 transactions?

Yes. Will do on Monday PT.

**Comment by ryandotsmith** [comment]
@raster21 added MaxPriorityFeePerGas, MaxFeePerGas in: 57fd7e5cfc7bf6aa2d19befdcffa9637532d5804

**Comment by raster21** [comment]
@ryandotsmith thanks! indexing worked, but filtering doesn't seem to work

**Comment by ryandotsmith** [comment]
It works for me. Can you share a snippet of your config? I'm wondering if you have multiple filters and one of them is causing the tx/event to pass.
