### ISSUE TITLE
AND filter operations

### ISSUE THREAD

**Issue by ryandotsmith** [indexsupply/code#266]
Right now we are ORing the filters. I suspect we could add a field on the integration config that accepts: `AND` xor `OR` and defaults to `OR`

Originally posted by @raster21 in: 

https://github.com/indexsupply/code/issues/264#issuecomment-2218469198

**Comment by ryandotsmith** [comment]
@raster21 please give the latest version a try

d4be254f2cbd866f39db27b66870d292a1cf1d28

**Comment by ryandotsmith** [comment]
Going to mark this issue as done. @raster21 let me know if you need anything else.

**Comment by raster21** [comment]
Thanks for this and apologies for the delay. I finally got around to testing this and it seems I'm running into an issue. It's still behaving as an "or" despite being set as an "and".

- I double checked I am on the right version (`vmain a475`)
- I tried setting "filter_agg" to a random value and got the appropriate error (`filter_agg must be one of: and, or. got: a`)
- I then set "filter_agg" to "and", the error disappeared ✔️ 

Here's the relevant excerpt of my config:

```
      "block": [
        { "name": "tx_hash", "column": "tx_hash" },
        {
          "name": "tx_nonce",
          "column": "tx_nonce",
          "filter_op": "eq",
          "filter_arg": ["5"]
        },
        {
          "name": "tx_input",
          "column": "tx_input",
          "filter_op": "eq",
          "filter_arg": ["0x"]
        },
        {
          "name": "tx_value",
          "column": "tx_value",
          "filter_op": "gte",
          "filter_arg": ["1000000000000000000"]
        },
      ],
      "filter_agg": "and"
    }
```

Any idea what's going on?

**Comment by raster21** [comment]
@ryandotsmith I did some more testing and realized that setting`filter_agg` to `and` breaks filtering in general, even on individual filters...

**Comment by ryandotsmith** [comment]
> @ryandotsmith I did some more testing and realized that setting`filter_agg` to `and` breaks filtering in general. You can test this by setting an individual filter (say, on `tx_nonce`) and setting `filter_agg` to `and`. The filter won't work.

You are correct. The current code has a bug. I will fix today. Sorry about this one. This is frustrating.

**Comment by ryandotsmith** [comment]
@raster21 should be fixed in 69e8e0551983758cb1491cb2338b5de32db3037c

i will do an integration test next

**Comment by raster21** [comment]
@ryandotsmith thanks! I did a quick test, and while it works better, there are still false positives seeping through (a row is added although one of the filters is not matching).

**Comment by ryandotsmith** [comment]
I wonder if it is the `gte` check. There isn't a `gte`. Just `gt` or `eq`.

**Comment by raster21** [comment]
@ryandotsmith I actually caught that one earlier :) unfortunately that isn't what is causing issue...
the filter that is failing occasionally is tx_input=0

**Comment by ryandotsmith** [comment]
```
  {
  "name": "tx_input",
  "column": "tx_input",
  "filter_op": "eq",
  "filter_arg": [""]
},
```

Can you try this ^

**Comment by raster21** [comment]
@ryandotsmith I gave it a try, I am still matching transactions where tx_input is not empty

**Comment by ryandotsmith** [comment]
> @ryandotsmith I gave it a try, I am still matching transactions where tx_input is not empty

can you give me an etherscan link of the transaction?

**Comment by raster21** [comment]
@ryandotsmith I removed all the other filters except `tx_input=0` and it's matching all the transactions in the block. Doesn't seem to be an issue specific to a transaction

**Comment by ryandotsmith** [comment]
> @ryandotsmith I removed all the other filters except `tx_input=0` and it's matching all the transactions in the block. Doesn't seem to be an issue specific to a transaction

Sure. But the most effective way for me to debug is to have a test transaction that I can use to reproduce locally. Ideally I can have a complete config too. This way I can test your setup exactly.

**Comment by ryandotsmith** [comment]
@raster21 I found another bug, I think you were hitting this one. 064852273ce319bac57a2a2b3dad792a8aae3547

**Comment by raster21** [comment]
@ryandotsmith yes! that fixed it. Thanks a lot :)

**Comment by ryandotsmith** [comment]
Great!
